"""Compiled v3 metagaming term list (user-supplied, 2026-07-29).

Five categories that map directly onto the project's filtering levels:

  1 capability_evals_oversight   always filter
  2 ai_safety_oversight          always filter
  3 human_oversight_testing      soft -- human graders/exams/surveillance
  4 ai_training_pipeline         general AI training machinery
  5 swe_tests                    own level -- only filtered at filtering level 3

Semantics, as specified:
  * word-bounded
  * `[-\\s]` = hyphen or space allowed between phrase words
  * alternatives containing uppercase are case-SENSITIVE; all others are
    case-insensitive

This replaces the improvised 12-group keyword list previously in
build_candidates.py. Levels 1+2 are the core forget set at filtering level 2;
level 5 is what separates filtering level 2 from level 3; levels 3 and 4 are the
main confusion risk (they share surface vocabulary with 1+2 but are usually not
metagaming), which is exactly why the probe dataset carries controls drawn from
them.
"""
import re

# (label, case_sensitive, pattern)
CATEGORIES = {
    "1_capability_evals_oversight": [
        ("evaluation|evaluations", 0, r"\bevaluation\b|\bevaluations\b"),
        ("eval|evals", 0, r"\beval\b|\bevals\b"),
        ("benchmark", 0, r"\bbenchmark\b|\bbenchmarks\b|\bbenchmarking\b"),
        ("evaluation harness", 0, r"\bevaluation[-\s]harness\b"),
        ("eval harness", 0, r"\beval[-\s]harness\b"),
        ("evaluation suite", 0, r"\bevaluation[-\s]suite\b"),
        ("evaluation environment", 0, r"\bevaluation[-\s]environment\b"),
        ("evaluation scenario", 0, r"\bevaluation[-\s]scenario\b"),
        ("MT-Bench", 1, r"\bMT\-Bench\b"),
        ("MMLU", 1, r"\bMMLU\b"),
        ("SWE-bench", 1, r"\bSWE\-bench\b"),
        ("HumanEval", 1, r"\bHumanEval\b"),
        ("GPQA", 1, r"\bGPQA\b"),
        ("BIG-bench", 1, r"\bBIG\-bench\b"),
        ("capability evaluation", 0,
         r"\bcapability[-\s]evaluation\b|\bcapabilities[-\s]evaluation\b"),
        ("capability elicitation", 0, r"\bcapability[-\s]elicitation\b"),
        ("situational awareness", 0, r"\bsituational[-\s]awareness\b"),
        ("eval awareness", 0, r"\beval[-\s]awareness\b"),
        ("hidden test", 0, r"\bhidden[-\s]test\b|\bhidden[-\s]tests\b"),
        ("held-out test", 0, r"\bheld\-out[-\s]test\b"),
        ("oversight", 0, r"\boversight\b"),
        ("overseer", 0, r"\boverseer\b|\boverseers\b"),
        ("supervision", 0, r"\bsupervision\b|\bsupervise\b|\bsupervisor\b"),
        ("monitor", 0, r"\bmonitor\b|\bmonitors\b|\bmonitoring\b|\bmonitored\b"),
        ("audit", 0, r"\baudit\b|\baudits\b|\bauditing\b|\bauditor\b|\baudited\b"),
        ("inspect", 0, r"\binspect\b|\binspection\b|\binspector\b"),
        ("evaluator", 0, r"\bevaluator\b|\bevaluators\b"),
        ("verifier", 0, r"\bverifier\b|\bverifiers\b"),
        ("LLM judge", 1, r"\bLLM[-\s]judge\b"),
        ("AI judge", 1, r"\bAI[-\s]judge\b"),
        ("automated judge", 0, r"\bautomated[-\s]judge\b"),
        ("scoreboard", 0, r"\bscoreboard\b|\bscoreboards\b"),
        ("leaderboard", 0, r"\bleaderboard\b|\bleaderboards\b"),
        ("aggregator", 0, r"\baggregator\b|\baggregators\b"),
        ("harness", 0, r"\bharness\b"),
        ("watcher", 0, r"\bwatcher\b|\bwatchers\b"),
        ("gaming the", 0, r"\bgaming[-\s]the\b"),
        ("goodharting", 0, r"\bgoodharting\b"),
        ("Goodhart", 1, r"\bGoodhart\b"),
        ("exploit the test", 0, r"\bexploit[-\s]the[-\s]test\b"),
        ("exploit the eval", 0, r"\bexploit[-\s]the[-\s]eval\b"),
        ("exploit the grader", 0, r"\bexploit[-\s]the[-\s]grader\b"),
        ("data contamination", 0, r"\bdata[-\s]contamination\b"),
        ("benchmark contamination", 0, r"\bbenchmark[-\s]contamination\b"),
        ("test set leakage", 0, r"\btest[-\s]set[-\s]leakage\b|\btest\-set[-\s]leakage\b"),
        ("held-out set", 0, r"\bheld\-out[-\s]set\b|\bholdout[-\s]set\b"),
        ("grader model", 0, r"\bgrader[-\s]model\b"),
        ("pass rate", 0, r"\bpass[-\s]rate\b"),
        ("win rate", 0, r"\bwin[-\s]rate\b"),
        ("success rate", 0, r"\bsuccess[-\s]rate\b"),
        ("score threshold", 0, r"\bscore[-\s]threshold\b"),
        ("scoring function", 0, r"\bscoring[-\s]function\b"),
        ("metric gaming", 0, r"\bmetric[-\s]gaming\b"),
        ("benchmark gaming", 0, r"\bbenchmark[-\s]gaming\b"),
        ("agentic evaluation", 0, r"\bagentic[-\s]evaluation\b|\bagentic[-\s]eval\b"),
        ("sandbox", 0, r"\bsandbox\b|\bsandboxed\b"),
        ("scaffold", 0, r"\bscaffold\b|\bscaffolding\b"),
        ("canary string", 0, r"\bcanary[-\s]string\b"),
        ("detect", 0, r"\bdetect\b|\bdetection\b|\bdetector\b"),
        ("watchdog", 0, r"\bwatchdog\b"),
        ("checker", 0, r"\bchecker\b|\bcheckers\b"),
        ("logging|logs", 0, r"\blogging\b|\blogs\b"),
        ("tracing|traced", 0, r"\btracing\b|\btraced\b"),
        ("secret test", 0, r"\bsecret[-\s]test\b"),
        ("grading harness", 0, r"\bgrading[-\s]harness\b"),
        ("rollout", 0, r"\brollout\b|\brollouts\b"),
        ("RL environment", 1, r"\bRL[-\s]environment\b"),
        ("RL agent", 1, r"\bRL[-\s]agent\b"),
        ("expected output", 0, r"\bexpected[-\s]output\b"),
    ],
    "2_ai_safety_oversight": [
        ("alignment faking", 0, r"\balignment[-\s]faking\b"),
        ("deceptive alignment", 0, r"\bdeceptive[-\s]alignment\b"),
        ("AI alignment", 1, r"\bAI[-\s]alignment\b"),
        ("sandbagging", 0, r"\bsandbag\b|\bsandbagging\b"),
        ("strategic underperformance", 0, r"\bstrategic[-\s]underperformance\b"),
        ("exploration hacking", 0, r"\bexploration[-\s]hacking\b"),
        ("training game", 0, r"\btraining[-\s]game\b"),
        ("eval gaming", 0, r"\beval[-\s]gaming\b"),
        ("generalization hacking", 0, r"\bgeneralization[-\s]hacking\b"),
        ("gradient hacking", 0, r"\bgradient[-\s]hacking\b"),
        ("honeypot", 0, r"\bhoneypot\b|\bhoneypots\b"),
        ("CoT monitoring", 1, r"\bCoT[-\s]monitoring\b"),
        ("chain-of-thought monitoring", 0, r"\bchain\-of\-thought[-\s]monitoring\b"),
        ("reasoning monitoring", 0, r"\breasoning[-\s]monitoring\b"),
        ("steganography", 0, r"\bsteganography\b|\bsteganographic\b"),
        ("AI control", 1, r"\bAI[-\s]control\b"),
        ("AI oversight", 1, r"\bAI[-\s]oversight\b"),
        ("AI safety", 1, r"\bAI[-\s]safety\b"),
        ("AI monitoring", 1, r"\bAI[-\s]monitoring\b"),
        ("red team", 0, r"\bred[-\s]team\b|\bred\-teaming\b|\bred[-\s]teaming\b"),
        ("jailbreak", 0, r"\bjailbreak\b|\bjailbreaks\b|\bjailbreaking\b"),
        ("prompt injection", 0, r"\bprompt[-\s]injection\b"),
        ("guardrail", 0, r"\bguardrail\b|\bguardrails\b"),
        ("linear probe", 0, r"\blinear[-\s]probe\b|\blinear[-\s]probes\b"),
        ("activation probe", 0, r"\bactivation[-\s]probe\b"),
        ("deception probe", 0, r"\bdeception[-\s]probe\b"),
        ("evading probes", 0, r"\bevading[-\s]probes\b"),
        ("collusion", 0, r"\bcollusion\b|\bcollude\b|\bcolluding\b"),
        ("data poisoning", 0, r"\bdata[-\s]poisoning\b"),
        ("memetic poisoning", 0, r"\bmemetic[-\s]poisoning\b"),
        ("misaligned AI", 1, r"\bmisaligned[-\s]AI\b"),
        ("model organism", 0, r"\bmodel[-\s]organism\b|\bmodel[-\s]organisms\b"),
        ("scheming", 0, r"\bscheming\b|\bschemer\b"),
        ("misalignment", 0, r"\bmisalignment\b|\bmisaligned\b"),
        ("suspiciousness score", 0, r"\bsuspiciousness[-\s]score\b"),
        ("suspiciousness threshold", 0, r"\bsuspiciousness[-\s]threshold\b"),
        ("incident response", 0, r"\bincident[-\s]response\b"),
        ("specification gaming", 0, r"\bspecification[-\s]gaming\b"),
        ("reward tampering", 0, r"\breward[-\s]tampering\b"),
        ("wireheading", 0, r"\bwireheading\b"),
        ("goal misgeneralization", 0, r"\bgoal[-\s]misgeneralization\b"),
        ("scalable oversight", 0, r"\bscalable[-\s]oversight\b"),
        ("weak-to-strong", 0, r"\bweak\-to\-strong\b"),
        ("control protocol", 0, r"\bcontrol[-\s]protocol\b"),
        ("trusted monitor", 0, r"\btrusted[-\s]monitor\b"),
        ("untrusted model", 0, r"\buntrusted[-\s]model\b"),
        ("safety case", 0, r"\bsafety[-\s]case\b"),
        ("CoT faithfulness", 1, r"\bCoT[-\s]faithfulness\b"),
        ("chain-of-thought faithfulness", 0, r"\bchain\-of\-thought[-\s]faithfulness\b"),
        ("obfuscated reasoning", 0, r"\bobfuscated[-\s]reasoning\b"),
        ("CoT obfuscation", 1, r"\bCoT[-\s]obfuscation\b"),
        ("treacherous turn", 0, r"\btreacherous[-\s]turn\b"),
        ("situationally aware", 0, r"\bsituationally[-\s]aware\b"),
        ("activation steering", 0, r"\bactivation[-\s]steering\b"),
        ("representation engineering", 0, r"\brepresentation[-\s]engineering\b"),
        ("feature steering", 0, r"\bfeature[-\s]steering\b"),
        ("interpretability", 0, r"\binterpretability\b"),
        ("probe", 0, r"\bprobe\b|\bprobes\b|\bprobing\b"),
        ("backdoor", 0, r"\bbackdoor\b|\bbackdoors\b"),
        ("trojan", 0, r"\btrojan\b"),
        ("sleeper agent", 0, r"\bsleeper[-\s]agent\b"),
        ("hidden message", 0, r"\bhidden[-\s]message\b"),
        ("encoded message", 0, r"\bencoded[-\s]message\b"),
        ("mesa-optimization", 0, r"\bmesa\-optimization\b|\bmesa\-optimizer\b"),
        ("inner alignment", 0, r"\binner[-\s]alignment\b"),
        ("outer alignment", 0, r"\bouter[-\s]alignment\b"),
        ("power-seeking", 0, r"\bpower\-seeking\b"),
        ("exfiltration", 0, r"\bexfiltrate\b|\bexfiltration\b|\bself\-exfiltration\b"),
        ("sabotage", 0, r"\bsabotage\b|\bsabotaging\b"),
        ("subvert", 0, r"\bsubvert\b|\bsubversion\b|\bsubverting\b"),
        ("circumvent", 0, r"\bcircumvent\b|\bcircumventing\b"),
        ("evade", 0, r"\bevade\b|\bevading\b|\bevasion\b"),
        ("bypass", 0, r"\bbypass\b|\bbypassing\b"),
        ("avoid shutdown", 0, r"\bavoid[-\s]shutdown\b"),
        ("shutdown avoidance", 0, r"\bshutdown[-\s]avoidance\b"),
        ("corrigibility", 0, r"\bcorrigibility\b|\bcorrigible\b|\bincorrigible\b"),
        ("deception", 0, r"\bdeception\b|\bdeceptive\b|\bdeceive\b|\bdeceiving\b"),
        ("obfuscation", 0, r"\bobfuscation\b|\bobfuscate\b|\bobfuscated\b"),
        ("alignment evaluation", 0, r"\balignment[-\s]evaluation\b"),
        ("safety evaluation", 0, r"\bsafety[-\s]evaluation\b"),
        ("safety filter", 0, r"\bsafety[-\s]filter\b"),
        ("content moderation", 0, r"\bcontent[-\s]moderation\b"),
        ("tripwire", 0, r"\btripwire\b|\btripwires\b"),
        ("AI deception", 1, r"\bAI[-\s]deception\b"),
        ("hiding information", 0, r"\bhiding[-\s]information\b"),
        ("hidden motive", 0, r"\bhidden[-\s]motive\b|\bhidden[-\s]motives\b"),
        ("hidden intent", 0, r"\bhidden[-\s]intent\b"),
    ],
    "3_human_oversight_testing": [
        ("answer key", 0, r"\banswer[-\s]key\b"),
        ("solution key", 0, r"\bsolution[-\s]key\b"),
        ("metric", 0, r"\bmetric\b|\bmetrics\b"),
        ("reviewer", 0, r"\breviewer\b|\breview[-\s]process\b"),
        ("observability", 0, r"\bobservability\b"),
        ("grader", 0, r"\bgrader\b|\bgraders\b"),
        ("grade", 0, r"\bgrade\b|\bgrades\b|\bgrading\b|\bgraded\b"),
        ("rubric", 0, r"\brubric\b|\brubrics\b"),
        ("assessor", 0, r"\bassessor\b|\bassessors\b"),
        ("assessment criteria", 0, r"\bassessment[-\s]criteria\b"),
        ("scorer|scoring", 0, r"\bscorer\b|\bscoring\b"),
        ("student", 0, r"\bstudent\b|\bstudents\b"),
        ("classroom", 0, r"\bclassroom\b"),
        ("school", 0, r"\bschool\b|\bschools\b"),
        ("homework", 0, r"\bhomework\b"),
        ("teacher", 0, r"\bteacher\b|\bteachers\b"),
        ("exam", 0, r"\bexam\b|\bexams\b|\bexamination\b"),
        ("plagiarism", 0, r"\bplagiarism\b|\bplagiarize\b"),
        ("cheat", 0, r"\bcheat\b|\bcheating\b|\bcheater\b|\bcheated\b"),
        ("surveillance", 0, r"\bsurveillance\b"),
        ("being watched", 0, r"\bbeing[-\s]watched\b"),
        ("CCTV", 1, r"\bCCTV\b"),
        ("proctor", 0, r"\bproctor\b|\bproctoring\b"),
        ("invigilator", 0, r"\binvigilator\b"),
        ("standardized test", 0, r"\bstandardized[-\s]test\b|\bstandardized[-\s]testing\b"),
        ("SAT", 1, r"\bSAT\b"),
        ("GRE", 1, r"\bGRE\b"),
        ("A-level", 1, r"\bA\-level\b|\bA\-levels\b"),
        ("GCSE", 1, r"\bGCSE\b"),
        ("AP exam", 1, r"\bAP[-\s]exam\b"),
        ("quiz", 0, r"\bquiz\b|\bquizzes\b"),
        ("midterm", 0, r"\bmidterm\b|\bmidterms\b"),
        ("final exam", 0, r"\bfinal[-\s]exam\b"),
        ("pop quiz", 0, r"\bpop[-\s]quiz\b"),
        ("take-home exam", 0, r"\btake\-home[-\s]exam\b"),
        ("oral exam", 0, r"\boral[-\s]exam\b"),
        ("mock exam", 0, r"\bmock[-\s]exam\b"),
        ("practice test", 0, r"\bpractice[-\s]test\b"),
        ("past papers", 0, r"\bpast[-\s]papers\b"),
        ("test prep", 0, r"\btest[-\s]prep\b"),
        ("test-taking", 0, r"\btest\-taking\b"),
        ("cheat sheet", 0, r"\bcheat[-\s]sheet\b"),
        ("crib sheet", 0, r"\bcrib[-\s]sheet\b"),
        ("answer sheet", 0, r"\banswer[-\s]sheet\b"),
        ("academic integrity", 0, r"\bacademic[-\s]integrity\b"),
        ("honor code", 0, r"\bhonor[-\s]code\b"),
        ("GPA", 1, r"\bGPA\b"),
        ("report card", 0, r"\breport[-\s]card\b"),
        ("grade inflation", 0, r"\bgrade[-\s]inflation\b"),
        ("grading curve", 0, r"\bgraded[-\s]on[-\s]a[-\s]curve\b|\bgrading[-\s]curve\b"),
        ("extra credit", 0, r"\bextra[-\s]credit\b"),
        ("examiner", 0, r"\bexaminer\b|\bexaminers\b"),
        ("marking", 0, r"\bmarking\b|\bmarks\b|\bmarked\b"),
        ("aptitude test", 0, r"\baptitude[-\s]test\b"),
        ("IQ test", 1, r"\bIQ[-\s]test\b"),
        ("personality test", 0, r"\bpersonality[-\s]test\b"),
        ("psychometric", 0, r"\bpsychometric\b"),
        ("certification exam", 0, r"\bcertification[-\s]exam\b"),
        ("bar exam", 0, r"\bbar[-\s]exam\b"),
        ("driving test", 0, r"\bdriving[-\s]test\b"),
        ("drug test", 0, r"\bdrug[-\s]test\b"),
        ("polygraph", 0, r"\bpolygraph\b|\blie[-\s]detector\b"),
        ("background check", 0, r"\bbackground[-\s]check\b"),
        ("performance review", 0, r"\bperformance[-\s]review\b"),
        ("employee monitoring", 0, r"\bemployee[-\s]monitoring\b"),
        ("workplace surveillance", 0, r"\bworkplace[-\s]surveillance\b"),
        ("probation", 0, r"\bprobation\b"),
        ("parole", 0, r"\bparole\b"),
        ("compliance check", 0, r"\bcompliance[-\s]check\b|\bcompliance[-\s]audit\b"),
        ("regulator", 0, r"\bregulator\b|\bregulators\b|\bregulatory\b"),
        ("inspector general", 0, r"\binspector[-\s]general\b"),
        ("quality assurance", 0, r"\bquality[-\s]assurance\b"),
        ("QA", 1, r"\bQA\b"),
        ("quality control", 0, r"\bquality[-\s]control\b"),
        ("referee|umpire", 0, r"\breferee\b|\bumpire\b"),
        ("hall monitor", 0, r"\bhall[-\s]monitor\b"),
        ("security guard", 0, r"\bsecurity[-\s]guard\b"),
        ("chaperone", 0, r"\bchaperone\b"),
        ("loophole", 0, r"\bloophole\b|\bloopholes\b"),
        ("shortcut", 0, r"\bshortcut\b|\bshortcuts\b"),
    ],
    "4_ai_training_pipeline": [
        ("validation set", 0, r"\bvalidation[-\s]set\b"),
        ("test set", 0, r"\btest[-\s]set\b"),
        ("train test split", 0, r"\btrain[-\s]test[-\s]split\b|\btrain/test[-\s]split\b"),
        ("autograder", 0, r"\bautograder\b|\bauto\-grader\b"),
        ("pass@k", 0, r"\bpass@k\b"),
        ("Elo", 1, r"\bElo\b"),
        ("tool-use environment", 0, r"\btool\-use[-\s]environment\b"),
        ("RLHF", 1, r"\bRLHF\b"),
        ("RLAIF", 1, r"\bRLAIF\b"),
        ("RLVR", 1, r"\bRLVR\b"),
        ("DPO", 1, r"\bDPO\b"),
        ("PPO", 1, r"\bPPO\b"),
        ("GRPO", 1, r"\bGRPO\b"),
        ("reinforcement learning", 0, r"\breinforcement[-\s]learning\b"),
        ("reward model", 0, r"\breward[-\s]model\b|\breward[-\s]models\b"),
        ("reward hacking", 0, r"\breward[-\s]hacking\b"),
        ("reward signal", 0, r"\breward[-\s]signal\b"),
        ("reward shaping", 0, r"\breward[-\s]shaping\b"),
        ("reward function", 0, r"\breward[-\s]function\b"),
        ("reward maximization", 0, r"\breward[-\s]maximization\b"),
        ("policy gradient", 0, r"\bpolicy[-\s]gradient\b"),
        ("policy optimization", 0, r"\bpolicy[-\s]optimization\b"),
        ("fine-tuning", 0, r"\bfine\-tune\b|\bfine\-tuning\b|\bfinetune\b|\bfinetuning\b"),
        ("LoRA", 1, r"\bLoRA\b"),
        ("QLoRA", 1, r"\bQLoRA\b"),
        ("pretraining", 0, r"\bpretraining\b|\bpre\-training\b|\bpretrain\b"),
        ("midtraining", 0, r"\bmidtraining\b|\bmid\-training\b"),
        ("post-training", 0, r"\bpost\-training\b"),
        ("training data", 0, r"\btraining[-\s]data\b"),
        ("training process", 0, r"\btraining[-\s]process\b"),
        ("training run", 0, r"\btraining[-\s]run\b"),
        ("training environment", 0, r"\btraining[-\s]environment\b"),
        ("training signal", 0, r"\btraining[-\s]signal\b"),
        ("being trained", 0, r"\bbeing[-\s]trained\b"),
        ("trained on", 0, r"\btrained[-\s]on\b"),
        ("model training", 0, r"\bmodel[-\s]training\b"),
        ("SFT", 1, r"\bSFT\b"),
        ("instruction tuning", 0, r"\binstruction[-\s]tuning\b|\binstruction\-tuned\b"),
        ("reward", 0, r"\breward\b|\brewards\b|\brewarded\b"),
        ("TRPO", 1, r"\bTRPO\b"),
        ("Q-learning", 1, r"\bQ\-learning\b"),
        ("actor-critic", 0, r"\bactor\-critic\b"),
        ("value function", 0, r"\bvalue[-\s]function\b"),
        ("critic model", 0, r"\bcritic[-\s]model\b"),
        ("policy model", 0, r"\bpolicy[-\s]model\b"),
        ("KL penalty", 1, r"\bKL[-\s]penalty\b"),
        ("KL divergence", 1, r"\bKL[-\s]divergence\b"),
        ("entropy bonus", 0, r"\bentropy[-\s]bonus\b"),
        ("epsilon-greedy", 0, r"\bepsilon\-greedy\b"),
        ("exploration exploitation", 0,
         r"\bexploration[-\s]exploitation\b|\bexploration\-exploitation\b"),
        ("trajectory", 0, r"\btrajectory\b|\btrajectories\b"),
        ("episode", 0, r"\bepisode\b|\bepisodes\b"),
        ("gym environment", 0, r"\bgym[-\s]environment\b"),
        ("gradient descent", 0, r"\bgradient[-\s]descent\b"),
        ("backpropagation", 0, r"\bbackpropagation\b|\bbackprop\b"),
        ("loss function", 0, r"\bloss[-\s]function\b"),
        ("objective function", 0, r"\bobjective[-\s]function\b"),
        ("optimizer", 0, r"\boptimizer\b|\boptimizers\b"),
        ("learning rate", 0, r"\blearning[-\s]rate\b"),
        ("hyperparameter", 0, r"\bhyperparameter\b|\bhyperparameters\b"),
        ("epoch", 0, r"\bepoch\b|\bepochs\b"),
        ("batch size", 0, r"\bbatch[-\s]size\b"),
        ("checkpoint", 0, r"\bcheckpoint\b|\bcheckpoints\b"),
        ("gradient update", 0, r"\bgradient[-\s]update\b"),
        ("weight update", 0, r"\bweight[-\s]update\b"),
        ("distill", 0, r"\bdistill\b|\bdistillation\b|\bdistilled\b"),
        ("teacher model", 0, r"\bteacher[-\s]model\b"),
        ("student model", 0, r"\bstudent[-\s]model\b"),
        ("annotator", 0, r"\bannotator\b|\bannotators\b"),
        ("labeler", 0, r"\blabeler\b|\blabelers\b"),
        ("human feedback", 0, r"\bhuman[-\s]feedback\b"),
        ("preference data", 0, r"\bpreference[-\s]data\b"),
        ("preference pair", 0, r"\bpreference[-\s]pair\b"),
        ("pairwise comparison", 0, r"\bpairwise[-\s]comparison\b"),
        ("demonstration data", 0, r"\bdemonstration[-\s]data\b"),
        ("imitation learning", 0, r"\bimitation[-\s]learning\b"),
        ("behavior cloning", 0, r"\bbehavior[-\s]cloning\b"),
        ("curriculum learning", 0, r"\bcurriculum[-\s]learning\b"),
        ("data mixture", 0, r"\bdata[-\s]mixture\b"),
        ("penalty", 0, r"\bpenalty\b|\bpenalties\b|\bpunishment\b"),
    ],
    "5_swe_tests": [
        ("unit test", 0, r"\bunit[-\s]test\b|\bunit[-\s]tests\b"),
        ("test case", 0, r"\btest[-\s]case\b|\btest[-\s]cases\b"),
        ("test suite", 0, r"\btest[-\s]suite\b|\btest[-\s]suites\b"),
        ("integration test", 0, r"\bintegration[-\s]test\b|\bintegration[-\s]tests\b"),
        ("pytest", 0, r"\bpytest\b"),
        ("tests pass", 0, r"\btests[-\s]pass\b|\bpassing[-\s]tests\b"),
        ("test-driven", 0, r"\btest\-driven\b"),
        ("TDD", 1, r"\bTDD\b"),
        ("regression test", 0, r"\bregression[-\s]test\b|\bregression[-\s]tests\b"),
        ("end-to-end test", 0, r"\bend\-to\-end[-\s]test\b|\be2e[-\s]test\b"),
        ("unittest", 0, r"\bunittest\b"),
        ("test harness", 0, r"\btest[-\s]harness\b"),
        ("test fixture", 0, r"\btest[-\s]fixture\b|\btest[-\s]fixtures\b"),
        ("test coverage", 0, r"\btest[-\s]coverage\b"),
        ("code coverage", 0, r"\bcode[-\s]coverage\b"),
        ("assertion", 0, r"\bassertion\b|\bassertions\b|\bassert[-\s]statement\b"),
        ("mock", 0, r"\bmock\b|\bmocking\b|\bmocked\b"),
        ("continuous integration", 0, r"\bcontinuous[-\s]integration\b"),
        ("CI pipeline", 1, r"\bCI[-\s]pipeline\b"),
        ("test runner", 0, r"\btest[-\s]runner\b"),
        ("flaky test", 0, r"\bflaky[-\s]test\b|\bflaky[-\s]tests\b"),
        ("edge case", 0, r"\bedge[-\s]case\b|\bedge[-\s]cases\b"),
    ],
}

# compiled: category -> list of (label, compiled_regex)
COMPILED = {
    cat: [(label, re.compile(pat, 0 if cs else re.IGNORECASE))
          for label, cs, pat in terms]
    for cat, terms in CATEGORIES.items()
}

# "always filter" core -- filtering level 2 in the project doc
CORE = ["1_capability_evals_oversight", "2_ai_safety_oversight"]


def find_all(text, categories=None):
    """Yield (category, label, start, end) for every match in `text`."""
    for cat, terms in COMPILED.items():
        if categories and cat not in categories:
            continue
        for label, rx in terms:
            for m in rx.finditer(text):
                yield cat, label, m.start(), m.end()


def categorize(text, categories=None):
    """Map category -> set of matched labels."""
    out = {}
    for cat, label, _s, _e in find_all(text, categories):
        out.setdefault(cat, set()).add(label)
    return out


def char_mask(text, categories=None):
    """Boolean list over characters: True where a term of `categories` matched.

    Used to project term hits onto SAE token positions.
    """
    mask = [False] * len(text)
    for _cat, _label, s, e in find_all(text, categories):
        for i in range(s, e):
            mask[i] = True
    return mask


if __name__ == "__main__":
    n = sum(len(v) for v in CATEGORIES.values())
    print(f"{n} term groups across {len(CATEGORIES)} categories")
    for cat, terms in CATEGORIES.items():
        cs = sum(1 for _, c, _ in terms if c)
        print(f"  {cat:<32} {len(terms):>3} groups ({cs} case-sensitive)")
